### ISSUE TITLE
Subtitles disappear on full-screen mode in Firefox

### ISSUE THREAD

**Issue by fletchgqc** [cgiffard/Captionator#27]
I noticed that in the demo. Is that related to Captionator?

**Comment by fletchgqc** [comment]
I noticed the same problem on the demo of Stories In Flight: http://www.storiesinflight.com/js_videosub/ and I've also seen this problem in MediaElement.js (though they talked about integrating captionator, perhaps they're now using your code anyway). So it seems to be a common problem on FireFox. But anyway, since captionator is the magic solution to all cross-browser problems, we shall have to solve it.

**Comment by cgiffard** [comment]
This is a broader issue, and not really a bug with Captionator, per se. Captionator isn't a video player, so it doesn't implement its own fullscreen functionality. However, this is _precisely_ what it would have to do in order to draw subtitles in fullscreen mode.

I've written players which can support fullscreen subtitles using Captionator - it's a feature entirely at the developer's discretion.

First of all, you need to override the functionality of the browser's native fullscreen control. You can do this by switching the 'controls' attribute off, and drawing your own controls on top. Then, put your video in a container (some kind of unsemantic division element would do the trick.) Tell Captionator to draw subs into this container with the runtime option `appendCueCanvasTo`.

Then, make your own fullscreen button using the [FullScreen API](http://updates.html5rocks.com/2011/10/Let-Your-Content-Do-the-Talking-Fullscreen-API) - which tells the _container_ to go fullscreen. Then, your captions will be visible in fullscreen view! :)

Let me know if you have any trouble getting this to work (I can go into more detail if you'd prefer.)

**Comment by fletchgqc** [comment]
Well in the end it was easier to go with a player that had it implemented already. But thanks a lot anyway.
